# Generated by Django 2.1 on 2019-02-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190225_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seats',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
