# Generated by Django 2.1.7 on 2019-02-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_booking_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodel',
            name='datetime',
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='date',
            field=models.DateField(default='1212-12-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='time',
            field=models.TimeField(default='11:11'),
            preserve_default=False,
        ),
    ]
